# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2a2de46253ba95bdaf0067dc6b53a4032946a875e5784222c002f951b8b0d4ac406b4689644628fa561d165e3a77f340596afc58b1bfc23b0beb342645719256

test:
  secret_key_base: 639e604410e9bc56a7cba4aabb1fc641a539f738bdac0c813d15580903ef3359aa9dd1cdf5c56307282815107bedc18b96d7eed7acb1f694c7f74eb5edbd83cf

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
